_layouts/default.html

Made some changes to the base layout file for the sidebar. Looks like this:

Some layout tweaks

---

index.md

Can tweak the HTML but this should be equivalent to what was there before.

Automatically generate the index page too

---

_posts/2018-06-10-update.md
_posts/2018-07-10-update.md
authors.md

How's this look to tide people over?

First pass on a post for this week.

---

_posts/2018-06-17-update.md

Still need to finish going through the doc PRs tonight but it's a start at least.

Update for June 17

---

_posts/2018-07-15-update.md

I still need to listen to the community meeting recording when I get home tonight, but it's a start for editing.

First pass on a post for July 15th

---

_posts/2019-02-03-update.md

No featured PRs in this edition because Noah is unavailable.

Publish Feb 3rd Edition

---

_posts/2019-03-31-update.md

If you want to get things pushed and I've not figured out the ServiceAccounts controller PR, feel free to yank that section, got plenty of others anyway.

Issue for March 31st

---

_posts/2019-04-14-update.md
template.md

Includes featured commit by @coderanger

April 14th Edition

---

CONTRIBUTING.md
README.md
SECURITY.md
SECURITY_CONTACTS.md
code-of-conduct.md

@coderanger please review
These should be all of the changes we need prior to putting the project under Kubernetes.

Submit kube

---

_posts/2021-01-31-update.md

@jberkus I found typo in 1/31 edition. could you take a look?? 🙇

2021-01-31: fix url of PR for denyserviceexternalips admission controller

---

README.md
authors.md
index.md

Update some links and language in the Readme to reflect status as a Kubernetes subproject.
Signed-off-by: Josh Berkus <josh@agliodbs.com>

Change subscription link to ButtonDown.

---

_posts/2020-03-08-update.md

Related:
- Part of: https://github.com/kubernetes/k8s.io/issues/1597

docs: follow kubernetes/k8s.io branch rename:

---

_posts/2021-11-28-update.md

Signed-off-by: Josh Berkus <josh@agliodbs.com>

Week Ending November 28, 2021

---

_posts/2022-03-13-update.md

Signed-off-by: Josh Berkus <josh@agliodbs.com>

March 13th issue

---

_posts/2022-03-27-update.md

Fingers crossed this just works this week.

Week Ending March 27, 2022

---

_posts/2022-04-24-update.md

Publish April 24th Edition

---

_posts/2022-05-15-update.md

Josh is in Valencia so flying solo this week.

Week Ending May 15, 2022

---

_posts/2022-07-10-update.md

July 10th edition

---

_posts/2022-08-28-update.md

August 28th Issue

---

_posts/2022-10-16-update.md

Oct 16th edition

---

_posts/2022-12-04-update.md

Short issue because of lack of PRs, Noah being out

Publish 12/4 edition

---

_posts/2023-05-28-update.md

Noah is out this week, so handling it solo.

Publish 5.28 issue

---

_posts/2023-07-09-update.md

July 9th edition is complete, merge and publish.

Merge July 9th edition

---

_posts/2023-09-10-update.md

Need to change the base branch to the to-be-created `20230910` branch before merging

Added KEP of the week for 09/10 issue

---

_posts/2023-09-24-update.md

Need to change the base branch to `20230924` once it is created
WIP.

Added release schedule for 09/24 issue

---

.github/ISSUE_TEMPLATE/lwkd-report.md

Please examine the following two points before merging this pr:
1. For Related projects, we need to link a list of projects from which we welcome submissions. Check [issue](https://github.com/kubernetes-sigs/lwkd/issues/232).
2. Is the label 'kind/feature' correct, or should it be changed to 'kind/documentation'?

Issue Template for LWKD Newsletter update request 

---

template.md

Added `KEP of the Week` and `Subprojects and Dependency Updates` sections to the template file
CC: @jberkus

Added KEP of the week and subproject updates to template.md

---

CONTRIBUTING.md
OWNERS_ALIASES
authors.md

@coderanger for your review.  Since we need both of them to be able to create branches for each release.

Add Fyka to OWNERS so that she can create branches too.

---

CONTRIBUTING.md

More internal docs for @fykaa and @sreeram-venkitesh

Add info on where to find Developer News

---

.github/workflows/get-releases-weekly.yaml
_posts/2024-01-07-update.md

Add Project updates to 20240107

Add Project updates

---

_posts/2024-01-14-update.md

Add legacy repository reminder & subproject updates to 20240114

Add legacy repository reminder & subproject updates to 20240114

---

_posts/2024-01-28-update.md

Add Contributor Summit updates

Add Contributor Summit updates

---

_posts/2024-02-11-update.md

Update Subprojects & Dependencies 20240211

Update Subprojects & Dependencies 20240211

---

_posts/2024-03-03-update.md

Add Subprojects and Dependency Updates for 2024-03-03

Add Subprojects and Dependency Updates for 2024-02-04

---

OWNERS_ALIASES
authors.md

Plus Mario and Satyam to Authors
Mario has been contributing for several weeks now, so it would be good to have him able to merge to issue branches.
@sreeram-venkitesh @fykaa please approve.

Add Mario to OWNERS

---

_posts/2024-03-24-update.md

[Add Developer News for KCSEU & adjecent Projekt updates for 03262024](https://github.com/kubernetes-sigs/lwkd/pull/333)

 Add Developer News for KCSEU & adjecent Projekt updates for 03262024

---

_posts/2024-03-31-update.md

Add updates of subproject and sig release survey

Add updates of subproject and sig release survey 

---

STYLESHEET.md

Add draft stylesheet info for subprojects.

---

_posts/2024-06-09-update.md

Original Post: https://lwkd.info/2024/20240611
Broken links reported in thread – https://kubernetes.slack.com/archives/C1TU9EB9S/p1718169248302239

[Week Ending June 9, 2024] fix links in section - other merges

---

OWNERS_ALIASES

syncing with current state :+1:

update contribex leads owners

---

_posts/2024-07-21-update.md

https://github.com/kubernetes/kubernetes/pull/126165

featured PR 24072024

---

scripts/release-crawler/main.go

Change Date & add links for releases

---

_posts/2024-09-01-update.md

ps: I can't find a patch release for this release schedule

release sched 01/09/2024

---

_posts/2024-09-08-update.md

Added Minikube release 1.34.0

---

scripts/release-crawler/README.md
scripts/release-crawler/main.go

This PR corrects cluster-api project path

Correct cluster-api project path

---

scripts/release-crawler/README.md
scripts/release-crawler/main.go

Tiny follow-up to https://github.com/kubernetes-sigs/lwkd/pull/432
Thanks!

crawler fix typo for Cluster API

---

STYLESHEET.md

This should help with writing those Patch Update entries.

Add a better template for patch releases.

---

_posts/2024-12-01-update.md

I don't seem to find any feature PR or merged feature/bug PR for this week/past 3 weeks apart from some cleanups. We can remove that section for this post.

remove featured prs/ merged prs

---

_posts/2024-12-15-update.md

featured PRs: 20241215

---

_posts/2025-01-19-update.md

featured PR: DRA CEL- Add Missing Size Estimator

---

_posts/2025-01-26-update.md

featured PR: add PodReplacementPolicy for Deployments: terminating pods

---

_posts/2025-04-27-update.md

Added featured PRs for 4/27 issue

Added featured PRs for 4/27 issue

---

_posts/2025-05-04-update.md

Add Featured PRs for 20250504 lwkd

Add Featured PRs for 20250504 lwkd

---

_posts/2025-05-11-update.md

Added featured PRs for 20250511 lwkd

Added featured PRs for 20250511 lwkd

---

_posts/2025-05-18-update.md

Added featured PRs for 20250518 lwkd

Added featured PRs for 20250518 lwkd

---

scripts/release-crawler/main.go

Which includes cluster-autoscaler, addon-resizer and vertical-pod-autoscaler
Context: https://kubernetes.slack.com/archives/C1TU9EB9S/p1747896265043799

Add the autoscaler repo

---

pre-commit.sh

Added pre-commit script to automate setting date in posts

---

_posts/2025-06-15-update.md

featured PRs for 20250615

---

_posts/2025-06-29-update.md

featured PRs for 20250629 LWKD

featured PRs for 20250629 LWKD

---

_posts/2025-07-06-update.md

Featured PRs for 20250706

---

_posts/2025-07-13-update.md

featured pr for 20250713

---

_posts/2025-07-20-update.md

featured pr for 20250720

---

_posts/2025-07-27-update.md

Featured PRs for 20250727

---

_posts/2025-08-24-update.md

featured pr for 20250824

---

_posts/2025-08-31-update.md

Featured PRs for 20250831
